CC = gcc
#CC = /usr/local/opt/llvm/bin/clang
CFLAGS = -O3 -fopenmp -L/usr/local/opt/llvm/lib -I/usr/local/opt/llvm/include

all: omp_example2 omp_example3

omp_example2: omp_example2.c
	$(CC) -o $@ $< $(CFLAGS)

omp_example3: omp_example3.c
	$(CC) -o $@ $< $(CFLAGS)

clean:
	rm -f omp_example2
	rm -f omp_example3
